from tkinter import *
window = Tk()
window.title("Mile to Km Converter")
window.minsize(width=500, height=300)
window.config(padx=20, pady=20)
mile = Entry(width=7)
mile.grid(row = 0, column = 1)
label_mile = Label(text="Miles")
label_mile.grid(row=0, column=2)
equal = Label(text = "is equal to")
equal.grid(row = 1, column = 0)
answer = Label(text="0")
answer.grid(row=1, column=1)
km = Label(text="Km")
km.grid(row = 1, column = 2)
def calculate():
    miles = float(mile.get())
    kms = round(miles * 1.60934)
    answer.config(text = f"{kms}")
calculate = Button(text =  "Calculate", command = calculate)
calculate.grid(row = 2, column = 1)
window.mainloop()
